# Generated by Django 4.1.6 on 2023-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
