# Generated by Django 4.1.6 on 2023-02-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userrwservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRwservation',
            new_name='UserReservation',
        ),
    ]
