# Generated by Django 4.1.6 on 2023-02-23 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_userrwservation_userreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='email',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Email in format *@*.*', regex='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(\\d{3}[-.]?){2}\\d{4}$')]),
        ),
    ]
